models/player.py
class Player:
    
    def __init__(self, team, name, position, id = None):
        self.team = team
        self.name = name
        self.position = position
        self.id = id

models/team.py
class Team:
    
    def __init__(self, name, stadium, wins, losses, id = None):
        self.name = name
        self.stadium = stadium
        self.wins= wins
        self.losses = losses
        self.id = id

app.py
from flask import Flask, render_template
app = Flask(__name__)
from controllers.players_controller import players_blueprint
from controllers.teams_controller import teams_blueprint
from controllers.standings_controller import standings_blueprint


@app.route('/')
def home():
    return render_template('index.html', title = "NBA Home Page")

if __name__ == '__main__':
    app.run(debug=True)

app.register_blueprint(players_blueprint)
app.register_blueprint(teams_blueprint)
app.register_blueprint(standings_blueprint)

controllers/players_controller.py
from models.player import Player
from flask import Flask, redirect, render_template, request
from flask import Blueprint
from repositories import player_repository
from repositories import team_repository
import pdb

players_blueprint = Blueprint("players", __name__)

#show players
@players_blueprint.route("/players")
def players():
    players = player_repository.select_all()
    return render_template("players/index.html", all_players = players, title = "NBA Player List")

#show player
@players_blueprint.route("/players/<id>", methods = ['GET'])
def show_player(id):
    player = player_repository.select(id)
    return render_template('players/show.html', player = player , title = player.name)

#new 
@players_blueprint.route("/players/new", methods=['GET'])
def new_player():
    teams = team_repository.select_all()
    return render_template("players/new.html", all_teams = teams, title = "Add new Player")

#create
@players_blueprint.route("/players", methods=['POST'])
def create_player():
    team = team_repository.select(request.form['team_id'])
    name = request.form['name']
    position = request.form['position']
    player = Player(team, name, position)
    player_repository.save(player)
    return redirect('/players')

#edit
@players_blueprint.route("/players/<id>/edit", methods = ['GET'])
def edit_player(id):
    player = player_repository.select(id)
    teams = team_repository.select_all()
    return render_template('players/edit.html', player = player, all_teams = teams, title = "Player Edit Page")

#update
@players_blueprint.route("/players/<id>", methods = ['POST'])
def update_player(id):
    # pdb.set_trace()
    team = team_repository.select(request.form['team_id'])
    name = request.form['name']
    position = request.form['position']
    player = Player(team, name, position, id)
    player_repository.update(player)
    return redirect('/players')

#delete
@players_blueprint.route("/players/<id>/delete", methods = ['GET'])
def delete_player(id):
    player_repository.delete(id)
    return redirect('/players')

#show players of a team
@players_blueprint.route("/players/team/<id>", methods = ['GET'])
def show_player_of_team(id):
    players = team_repository.players(id)
    return render_template('/players/team_players.html', players = players, title = "Full Roster")

controllers/standings_controller.py
from models.player import Player
from models.team import Team
from flask import Flask, redirect, render_template, request
from flask import Blueprint
from repositories import player_repository
from repositories import team_repository
from repositories import standings_repository
import pdb

standings_blueprint = Blueprint("standings", __name__)

@standings_blueprint.route("/standings")
def standings():
    teams = standings_repository.order_teams()
    return render_template("standings/index.html", all_teams = teams, title = "Standings")

controllers/teams_controller.py
from models.player import Player
from flask import Flask, redirect, render_template, request
from flask import Blueprint
from models.team import Team
from repositories import player_repository
from repositories import team_repository
import pdb

teams_blueprint = Blueprint("teams", __name__)

#show teams
@teams_blueprint.route("/teams")
def teams():
    teams = team_repository.select_all()
    return render_template("teams/index.html", all_teams = teams, title = "NBA Teams")

#show team
@teams_blueprint.route("/teams/<id>", methods = ['GET'])
def show_team(id):
    team = team_repository.select(id)
    players = team_repository.players(id)
    return render_template('teams/show.html', team = team, players = players, title = team.name)

#new team
@teams_blueprint.route("/teams/new", methods = ['GET'])
def new_team():
    teams = team_repository.select_all()
    return render_template("teams/new.html", all_teams = teams, title = "Add new Team")


#create team
@teams_blueprint.route("/teams", methods = ['POST'])
def create_team():
    name = request.form['name']
    stadium = request.form['stadium']
    wins = request.form['wins']
    losses = request.form ['losses']
    team = Team(name, stadium, wins, losses)
    team_repository.save(team)
    return redirect('/teams')

#edit team
@teams_blueprint.route("/teams/<id>/edit", methods = ['GET'])
def edit_team(id):
    team = team_repository.select(id)
    return render_template('teams/edit.html', team = team, title = "Team Edit Page")

#update team
@teams_blueprint.route("/teams/<id>/update", methods = ['POST'])
def update_team(id):
    name = request.form['name']
    stadium = request.form['stadium']
    wins = request.form['wins']
    losses = request.form['losses']
    team = Team(name, stadium, wins, losses, id)
    team_repository.update(team)
    return redirect('/teams')

#delete team
@teams_blueprint.route("/teams/<id>/delete", methods = ['GET'])
def delete_team(id):
    team_repository.delete(id)
    return redirect('/teams')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{{ title }}</title>
</head>
<body>
  <link rel="stylesheet" href="static/style.css">
    <header>
        <nav>
          <ul class="menu">
            <ul><a href="{{ url_for('home') }}">Home</a></ul>
            <ul><a href="{{ url_for('teams.teams') }}">Teams</a></ul>
            <ul><a href="{{ url_for('standings.standings') }}">Standings</a></ul>
            <ul><a href="{{ url_for('players.players') }}">Players</a></ul>
            <ul><a href="https://www2.nbastore.eu/en/?loc=en-GB?_s=bm-fi-NBA-prtsite-NBA-PS-1020US">NBA Store</a> </ul>
            <ul><a href="https://watch.nba.com/packages?ls=nba:leaguepass:own:dig:intsites:topnav:eg:acq:sub:dtc-acq:skysports:UK:en:">NBA League Pass</a> </ul>
          </ul>
        </nav>
    </header>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
    
      {%block home%}
      {% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block home %}


<div class="match_info">
    <div>
        <h3><u>Today's Matches</u></h3>
        <div> </div>
        <p>Toronto Raptors vs Chicago Bulls 7:00 pm</p>
        <p>L.A Lakers vs Los Angeles Clippers 8:30 pm</p>
        <p>Brooklyn Nets vs Miami Heat 10:00 pm</p>

    </div>
</div>
<div class="result_info">  
    <div>
        <h3><u>Results</u></h3>
        <p>Toronto Raptors 124-120 Miami Heat</p>
        <li><a href="https://www.youtube.com/watch?v=ewg2Cm0JNxc">Raptors vs Heat Full Game Highlights</a></li>
        <p>Brooklyn Nets 106-110 Golden State Warriors</p>
        <li><a href="https://www.youtube.com/watch?v=IK-8Hxj4ysY">Nets vs Warriors Full Game Highlights</a></li>
        <p>Boston Celtics 107-97 New Orleans Pelicans</p>
        <li><a href="https://www.youtube.com/watch?v=Nh6YdD7Ia_Y">Nets vs Warriors Full Game Highlights</a></li>
        <p>Indiana Pacers 105-132 Dallas Mavericks</p>
        <li><a href="https://www.youtube.com/watch?v=efS_UwIfiyM">Nets vs Warriors Full Game Highlights</a></li>
    </div>
</div>
<div class="top_plays">    
    <div>
        <h3><u>Top Plays</u></h3>
        <li><a href="https://www.youtube.com/watch?v=eqeRDDT11R4">Top 10 Plays of The Night: January 29</a></li>
        <li><a href="https://www.youtube.com/watch?v=k0RUeeny-B8">Top 10 Plays of The Night: January 30</a></li>
        <li><a href="https://www.youtube.com/watch?v=k2w5YmWUBlM">Top 5 Dunks of The Night: January 29</a></li>
    </div>
</div>
<img class="jordan" src="/static/air_jordan.png">
<div class="headline">
    <ul><u>Headlines</u></ul>
</div>
    <div class="headline_titles">
        <li><a href="https://www.nba.com/watch/video/curry-drains-7-threes-scores-21-of-his-40-points-in-4th-in-win-over-rockets">Curry lights up Rockets for 21 in 4th, 40 overall</a></li>
        <li><a href="https://www.nba.com/news/hawks-trae-young-sidelined-with-shoulder-contusion">Hawks' Young (shoulder) misses game vs. Raptors</a>/li>
        <li><a href="https://www.nba.com/news/joe-ingles-exits-game-with-left-knee-injury-will-undergo-mri">Jazz's Ingles (torn left ACL) out for season</a></li>
        <li><a href="https://www.nba.com/news/wizards-bradley-beal-wrist-to-miss-next-2-games">Beal to get further evaluation on wrist injury</a></li>
        <li><a href="https://www.nba.com/watch/video/20220131gttorontoraptors">How should Raptors approach trade deadline?</a></li>
        <li><a href="https://www.nba.com/news/power-rankings-2021-22-week-16">Power Rankings: Red-hot Suns hold No. 1 spot</a></li>
        <li><a href="https://www.nba.com/news/nba-players-week-chris-paul-joel-embiid">Embiid, Paul named Players of the Week</a></li>
        <li><a href="https://www.nba.com/news/tyler-herro-returns-to-form-enters-all-star-chase-with-bounce-back-season">Herro's game back in tune once again for Miami</a></li>
        <li><a href="https://www.nba.com/news/nba-league-pass-games-to-watch-week-16-of-2021-22-season">10 must-see games on League Pass this week</a></li>
        <li><a href="https://www.nba.com/news/2022-all-star-starters-revealed">2022 NBA All-Star Game starters revealed</a></li>
    </div>
</div>



<footer>
    <p>Terms & Conditions</p>
    <p>Privacy & Cookies Notice</p>
    <p>Privacy Options</p>
    <p>Accessibility Information</p>
    <p>Contact Us</p>
</footer>

{% endblock %}

templates/players/edit.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<div class="update_player">
<form action="/players/{{player.id}}" method="post">
    <div>
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" value="{{player.name}}" required autofocus>
    </div>
    <div>
        <label for="team">Team:</label>
        <select id="team" name="team_id">
            {% for team in all_teams %} 
                <option value="{{team.id}}"
                    {% if player.team.id == team.id %} selected="selected" {% endif %}>
                    {{ team.name }}
                </option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label for ="position">Position:</label>
        <input type="text" id="position" name="position" value="{{player.position}}" required autofocus>  
    </div>

    <button type="submit">Update Player</button>
</form>
</div>


{% endblock %}

templates/players/index.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

    <div id="grid_players">
        {% for player in all_players %}
        <div>
        <a href="/players/{{player.id}}">{{player.name}}</a>
        </div>
        {% endfor %}
    </div>
{% endblock %}

templates/players/new.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<div class="add_player">
<form action="/players" method="post">
    <div>
        <label for="name">Name</label>
        <input type="text" id="name" name="name" placeholder="Name" required autofocus>
    </div>
    <div>
        <label for="team">Team:</label>
        <select id="team" name="team_id">
            {% for team in all_teams %}
                <option value="{{ team.id }}">{{ team.name }}</option>
            {% endfor %}
        </select>
    </div>
    <div>
        <label for="position">Position:</label>
        <input type="text" id="position" name="position" placeholder="Position" required autofocus>
    </div>
    <button type="submit">Add Player</button>
</form>
</div>


{% endblock %}

templates/players/show.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<div class="player_details">
    <ul>{{player.name}}</ul>
    <p>
        <ul>Team: {{player.team.name}}</ul>
        <ul>Position: {{player.position}}</ul>
    </p>
</div>
<div class="player_buttons">
    <p>
        <a href="/players/{{player.id}}/edit">Edit Player</a>
    </p>
    <p>
        <a href="/players/{{player.id}}/delete">Remove Player</a>
    </p>
</div>

{% endblock %}

templates/players/team_players.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<div class="team_players">
    <h1>Full Roster</h1>
{% for player in players %}
    <div class="team_list">
        {{player.name}} {{player.position}}
    </div>    
{% endfor %}
</div>


{% endblock %}

templates/standings/index.html
{% extends "base.html" %}
{% block home %}

<h2>Standings</h2>
<div id="grid_standings">

    {% for team in all_teams %}
    
    <div>
      {{loop.index}} {{ team.name }} : {{ team.wins }} - {{ team.losses }} 
    </div>

    {% endfor %}
</div>

{% endblock %} 

templates/teams/edit.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="/static/style.css">
<div class="update_team">
<form action="/teams/{{team.id}}/update" method="post">
    <div>
        <labe for="name">Name:</labe>
        <input type="text" id="name" name="name" value="{{team.name}}" required>
    </div>
    <div>
        <label for="stadium">Stadium:</label>
        <input type="text" id="stadium" name="stadium" value="{{team.stadium}}" required>
    </div>
    <div>
        <label for="wins">Wins:</label>
        <input type="number" id="wins" name="wins" value="{{team.wins}}" required autofocus>
    </div>
    <div>
        <label for="losses">Losses:</label>
        <input type="number" id="losses" name="losses" value="{{team.losses}}" required autofocus>
    </div>
    <button type="submit">Update Team</button>
</div>

</form>




{% endblock %}

templates/teams/index.html
{% extends "base.html" %}
{% block content %}

<div id="grid_teams">
    {% for team in all_teams %}
    <div>
    <a href="/teams/{{ team.id }}">{{ team.name }}</a> 
    </div>
    {% endfor %}
</div>
<div class="add_team">
    <p>
        <li><a href="{{ url_for('teams.new_team') }}">Add a Team</a></li>
    </p>    
</div>

{% endblock %}

templates/teams/new.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="/static/style.css">
<div class="new_team">
<form action="/teams" method="post">
    <div>
        <label for="name">Name:</label>
        <input type="text" id="title" name="name" placeholder="Name" required autofocus>
    </div>
    <div>
        <label for="stadium">Stadium:</label>
        <input type="text" id="stadium" name="stadium" placeholder="Stadium" required autofocus>
    </div>
    <div>
        <label for="wins">Wins:</label>
        <input type="number" id="wins" name="wins" placeholder="Wins" required>
    </div>
    <div>
        <label for="losses">Losses:</label>
        <input type="number" id="losses" name="losses" placeholder="Losses" required>
    </div>

    <button type="submit">Add New Team</button>
</form>
</div>

{% endblock %}

templates/teams/show.html
{% extends "base.html" %}
{% block content %}

<link rel="stylesheet" href="/static/style.css">

<div class="team_logo">
    <img src="/static/team_images/{{team.name}}.png">
</div>
<div class="team_details">
    <div class="stadium">
        Stadium: {{ team.stadium }}
    </div>
    <div class="score">
    Total: {{ team.wins }} wins - {{ team.losses }} losses
    </div>
</div>
<div class="starting_lineup">
        <h1>Starting Lineup</h1>
            {% for player in players %} 
        <li> {{player.name}} - {{player.position}}</li>
            {% endfor %} 
        <p>
            <a href="/players/team/{{team.id}}">View Full Roster</a>
        </p>
</div>
<div class="team_buttons">
    <p>
        <a href="/teams/{{team.id}}/edit">Edit Team</a>
    </p>
    <p>
        <a href="/teams/{{team.id}}/delete">Remove Team</a>
    </p>
    <p>
        <a href="{{ url_for('players.new_player') }}">Add a Player</a>
    </p>
</div>
        


{% endblock %}